import novel1 from '../assets/covers/novel1.png'
import novel2 from '../assets/covers/novel2.png'
import novel3 from '../assets/covers/novel3.png'
import novel4 from '../assets/covers/novel4.png'
import novel5 from '../assets/covers/novel5.png'
import novel6 from '../assets/covers/novel6.png'
import novel7 from '../assets/covers/novel7.png'
import novel8 from '../assets/covers/novel9.png'
import novel9 from '../assets/covers/novel9.png'

const novels = [
  {
    id: 1,
    name: 'Solo Leveling',
    image: novel1,
    country: 'Korea',
    author: 'Zoi4erom',
    status: 'Завершено',
    genres: 'екшен, фентезі, підземелля, система розвитку',
    tags: 'мисливці, монстри, система',
    views: 56320,
    updated: '4 дня назад',
    description: 'У світі, де після появи порталів із монстрами люди отримали надздібності...',
  },
  {
    id: 2,
    name: 'Tokyo Ghoul',
    image: novel2,
    country: 'Japan',
    author: 'Ishida Sui',
    status: 'Завершено',
    genres: 'хоррор, екшен',
    tags: 'гули, драма',
    views: 40210,
    updated: '2 дні назад',
    description: 'Історія про світ, де люди і гули співіснують...',
  },
  {
    id: 3,
    name: 'Eat of Dragons',
    image: novel3,
    country: 'Korea',
    author: 'Sing Shong',
    status: 'Онгоінг',
    genres: 'фентезі, апокаліпсис',
    tags: 'система, виживання',
    views: 78900,
    updated: '1 день назад',
    description: 'Кім Докча був єдиним читачем веб-новели...',
  },
  {
    id: 4,
    name: 'Gift of Moon',
    image: novel4,
    country: 'Korea',
    author: 'Sing Shong',
    status: 'Онгоінг',
    genres: 'фентезі, апокаліпсис',
    tags: 'система, виживання',
    views: 78900,
    updated: '1 день назад',
    description: 'Кім Докча був єдиним читачем веб-новели...',
  },
  {
    id: 5,
    name: 'Omniscient Reader',
    image: novel5,
    country: 'Korea',
    author: 'Sing Shong',
    status: 'Онгоінг',
    genres: 'фентезі, апокаліпсис',
    tags: 'система, виживання',
    views: 78900,
    updated: '1 день назад',
    description: 'Кім Докча був єдиним читачем веб-новели...',
  },
  {
    id: 6,
    name: 'Solo Leveling',
    image: novel6,
    country: 'Korea',
    author: 'Sing Shong',
    status: 'Онгоінг',
    genres: 'фентезі, апокаліпсис',
    tags: 'система, виживання',
    views: 78900,
    updated: '1 день назад',
    description: 'Кім Докча був єдиним читачем веб-новели...',
  },
  {
    id: 7,
    name: 'Tokyo Ghoul',
    image: novel7,
    country: 'Japan',
    author: 'Ishida Sui',
    status: 'Завершено',
    genres: 'хоррор, екшен',
    tags: 'гули, драма',
    views: 40210,
    updated: '2 дні назад',
    description: 'Історія про світ, де люди і гули співіснують...',
  },
  {
    id: 8,
    name: 'Tokyo Ghoul 2',
    image: novel9,
    country: 'Japan',
    author: 'Ishida Sui',
    status: 'Завершено',
    genres: 'хоррор, екшен',
    tags: 'гули, драма',
    views: 40210,
    updated: '2 дні назад',
    description: 'Історія про світ, де люди і гули співіснують...',
  },
  {
    id: 9,
    name: 'Tokyo Ghoul 2',
    image: novel3,
    country: 'Japan',
    author: 'Ishida Sui',
    status: 'Завершено',
    genres: 'хоррор, екшен',
    tags: 'гули, драма',
    views: 40210,
    updated: '2 дні назад',
    description: 'Історія про світ, де люди і гули співіснують...',
  },
]

export default novels
